services:
  postgres:
    image: postgres:16-alpine
    container_name: user-activity-postgres
    environment:
      POSTGRES_DB: user_activity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '54332:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-activity-network

  redis:
    image: redis:7-alpine
    container_name: user-activity-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - user-activity-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-activity-app
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    networks:
      - user-activity-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  user-activity-network:
    driver: bridge
